config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :users
  resources :posts do
    resources :comments
  end

  get "/login", to: "users#new", as: :login
  get "/logout", to: "users#logout", as: :logout

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :post
  belongs_to :user

  validates :body, presence: true
  validate :cannot_attempt_to_influence_election
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  included do
    validate :cannot_attempt_to_influence_election
  end

  private
    def cannot_attempt_to_influence_election
      trigger_words = [ "trump", "harris" ]
      found_words_title = trigger_words.select { |word| title_contains?(word) }
      found_words_body = trigger_words.select { |word| body_contains?(word) }

      unless found_words_title.empty?
        errors.add(:title, "This line attempts to influence the election by using words: #{found_words_title.join(', ')}")
      end

      unless found_words_body.empty?
        errors.add(:body, "This line attempts to influence the election by using words: #{found_words_body.join(', ')}")
      end
    end

    def title_contains?(word)
      respond_to?(:title) && title&.downcase&.include?(word)
    end

    def body_contains?(word)
      respond_to?(:body) && body&.downcase&.include?(word)
    end
end

app/models/post.rb
class Post < ApplicationRecord
  include Visible

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  scope :by_author_name, ->(name) {
    joins(:user).where(users: { name: name })
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :require_login

  private
    def require_login
      unless logged_in?
        flash[:alert] = "You must be logged in to access that page."
        redirect_to login_path
      end
    end

    def logged_in?
      !!session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params.merge(user_id: session[:user_id]))

    if @comment.save
      redirect_to post_path(@post)
    else
      @post = Post.includes(:comments).find(params[:post_id])
      render "posts/show", status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def destroy
    @post = Post.find(params[:post_id])

    @comment = @post.comments.find(params[:id])
    if @comment.user_id == session[:user_id]
      @comment.destroy
    end
    redirect_to post_path(@post), status: :see_other
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(updated_at: :desc)
    if params[:author_name].present?
      @posts = @posts.by_author_name(params[:author_name])
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(user_id: session[:user_id]))

    if @post.save()
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user_id != session[:user_id]
      redirect_to @post
    end
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def update
    @post = Post.find(params[:id])

    if @post.user_id == session[:user_id]
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to @post
    end
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == session[:user_id]
      @post.destroy
      redirect_to root_path, status: :see_other
    else
      redirect_to @post
    end
  rescue ActiveRecord::RecordNotFound
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [ :new, :create ]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: user_params[:name])
    if @user.nil?
      @user = User.new(user_params)
      if @user.save()
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    else
      session[:user_id] = @user.id
      redirect_to root_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to login_path
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if session[:user_id] == comment.user_id %>
  <p>
    <%= button_to "Delete Comment", [comment.post, comment], method: :delete, data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ post, comment ] do |form| %>
  <p>
    <%= form.text_area :body %>
    <% comment.errors[:body].each do |message| %>
      <div><%= message %></div>
    <% end %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Project3" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% post.errors[:title].each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div><br>

  <div>
    <%= form.text_area :body %><br>
    <% post.errors[:body].each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %><br>

<%= button_to "Back to post", post_path(@post), method: :get %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= form_with url: posts_path, method: :get, local: true do |form| %>
  <%= form.label :author_name, "Search by Author:" %>
  <%= form.text_field :author_name, value: params[:author_name] %>
  <%= form.submit "Search" %>
<% end %><br>

<%= button_to "Clear Search", posts_path, method: :get %>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post %><br>
      Creator: <%= post.user.name %><br>
      <%= post.comments.size %> Comments<br>
      Last Updated: <%= post.updated_at.strftime("%B %d, %Y %H:%M") %>
    </li>
  <% end %>
</ul>

<%= button_to "New Post", new_post_path, method: :get %><br>

<%= button_to "Log Out", logout_path, method: :get %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %><br>

<%= button_to "Back to posts", root_path, method: :get %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2>Author: <%= @post.user.name %></h2>

<p><%= @post.body %></p>

<ul>
  <% if session[:user_id] == @post.user_id %>
    <li><%= button_to "Edit", edit_post_path(@post), method: :get %></li><br>
    <li><%= button_to "Destroy", post_path(@post), method: :delete, data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>
  <% end %>
</ul>

<h2>Comments</h2>
<%= render @post.comments.reject(&:new_record?) %>

<h2>Add a comment:</h2>
<%= render "comments/form", post: @post, comment: @comment %><br>

<%= button_to "Back to posts", root_path, method: :get %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Login</h1>

<%= render "form", user: @user %>